---
version: 2.1

executors:
  golang:
    docker:
    - image: circleci/golang:1.13

jobs:
  test:
    executor: golang

    steps:
      - checkout
      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: go test -v ./...

  build_release_on_tag:
    executor: golang

    steps:
    - checkout
    - attach_workspace:
        at: .
    - run: ./release/get.sh
    - run: ./release/publish.sh --tag $CIRCLE_TAG

workflows:
  version: 2
  multiwerf:
    jobs:
    # run tests on every commit
    - test:
        filters:  # required since `build_release_on_tag` has tag filters AND requires `test`
          tags:
            only: /.*/
          branches:
            only: /.*/
    # test, build and publish release on every semver tag
    - build_release_on_tag:
        requires:
        - test
        filters:
          tags:
            only: /^v[0-9]+(\.[0-9]+){2}([-+].+|[^-.]*)$/
          branches:
            ignore: /.*/

