name: Experimental releaser
on:
  push:
    branches:
    - experimental
jobs:
  create_experimental_release:
    name: Create experimental multiwerf release
    runs-on: ubuntu-latest
    steps:
    - name: Create release tag
      run: |
        set -e

        echo "Setting up multiwerf git repo ..."
        git clone https://flant-team-sysdev:${{ secrets.FLANT_TEAM_SYSDEV_TOKEN }}@github.com/flant/multiwerf.git
        cd multiwerf
        git -c advice.detachedHead=false checkout $GITHUB_SHA
        git config user.name flant-team-sysdev
        git config user.email team-sysdev+github@notice.flant.com

        echo "Releasing experimental tag ..."
        ./scripts/create_release_tag.sh :experimental
      shell: bash
