name: Experimental releaser
on:
  push:
    branches:
    - experimental

jobs:
  create_experimental_release:
    name: Create experimental multiwerf release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Create release tag
      run: |
        git config user.name github-experimental-releaser
        git config user.email 256@flant.com
        ./scripts/create_release_tag.sh :experimental
      shell: bash
