name: Experimental releaser
on:
  push:
    branches:
    - experimental
jobs:
  create_experimental_release:
    name: Create experimental multiwerf release
    runs-on: ubuntu-latest
    steps:
    - name: Create release tag
      run: |
        set -e

        git clone https://$EXPERIMENTAL_RELEASER_USER_NAME:$EXPERIMENTAL_RELEASER_PASSWORD@github.com/flant/multiwerf.git
        cd multiwerf
        git -c advice.detachedHead=false checkout $GITHUB_SHA

        git config user.name $EXPERIMENTAL_RELEASER_USER_NAME
        git config user.email $EXPERIMENTAL_RELEASER_USER_EMAIL

        ./scripts/create_release_tag.sh :experimental
      shell: bash
      env:
        EXPERIMENTAL_RELEASER_USER_NAME: ${{ secrets.EXPERIMENTAL_RELEASER_USER_NAME }}
        EXPERIMENTAL_RELEASER_USER_PASSWORD: ${{ secrets.EXPERIMENTAL_RELEASER_USER_PASSWORD }}
        EXPERIMENTAL_RELEASER_USER_EMAIL: ${{ secrets.EXPERIMENTAL_RELEASER_USER_EMAIL }}
