name: Run tests
on:
  pull_request:
    branches:
      - master
env:
  GO111MODULE: on

jobs:

  unit_tests:
    name: Unit tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Checkout code
        uses: actions/checkout@v1

      - name: Test
        run: go test ./pkg/... ./cmd/...
        shell: bash

  integration_tests:
    name: Integration tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Checkout code
        uses: actions/checkout@v1

      - name: Test
        run: go test ./integration/...
        shell: bash