name: Tests
on:
  pull_request:
    branches:
      - master
env:
  GO111MODULE: on

jobs:

  tests:
    name: Go Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Checkout code
      uses: actions/checkout@v1

    - name: Run tests
      run: go test ./...
