name: Run tests
on:
  pull_request:
    branches:
      - master
env:
  GO111MODULE: on

jobs:

  tests:
    name: Tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        shell: [sh, bash, cmd, powershell]
        exclude:
        - os: ubuntu-latest
          shell: cmd
        - os: ubuntu-latest
          shell: powershell
        - os: macOS-latest
          shell: cmd
        - os: macOS-latest
          shell: powershell
        - os: windows-latest
          shell: sh

    runs-on: ${{ matrix.os }}
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Checkout code
      uses: actions/checkout@v1

    - name: Test
      run: go test ./...
      shell: "${{ matrix.shell }}"
